import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'app-nav-bar',
  templateUrl: './nav-bar.component.html',
  styleUrls: ['./nav-bar.component.scss']
})
//This line below generated by tool
export class NavBarComponent implements OnInit {

  constructor() { }

  ngOnInit(): void {
  }

}
